version: "3.9"
services:
  Oracle_XE:
    container_name: oracle_xe
    image: container-registry.oracle.com/database/express:21.3.0-xe
    volumes:
      - ./data:/opt/oracle/oradata
    ports:
      - "1521:1521"
      - "5500:5500"
    env_file:
      - oracle_db.env