version: "3.9"
services:
  ne04j:
    container_name: neo4j
    image: neo4j:5.3.0
    volumes:
      - ./data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - neo4j_db.env