ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP USER STUDENT_DB CASCADE;
CREATE USER STUDENT_DB IDENTIFIED BY STUDENT_DB;
GRANT CREATE SESSION TO STUDENT_DB;
GRANT UNLIMITED TABLESPACE TO STUDENT_DB;
GRANT CREATE TABLE TO STUDENT_DB;

-------------------------------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA = STUDENT_DB;

CREATE TABLE FACULTY (
    FACULTY_LETTER   VARCHAR2(5),
    FACULTY_NAME_RU  VARCHAR2(200),
    FACULTY_NAME_EN  VARCHAR2(200)
);

CREATE TABLE STUDENT (
    STUDENT_ID   NUMBER(10,0),
    GROUP_CODE   VARCHAR2(20)
);

CREATE TABLE TEST (
    TEST_ID        NUMBER(10,0),
    TEST_NAME_RU   VARCHAR2(200),
    TEST_NAME_EN   VARCHAR2(200)
);

CREATE TABLE STUDENT_TEST (
    STUDENT_ID     NUMBER(10,0),
    TEST_ID        NUMBER(10,0),
    SCORE          NUMBER(3,0)
);

create table FACULTY_TRANSLATE (
    Faculty_Name_Ru  varchar2(200),
    Faculty_Name_En  varchar2(200)
);

create table TEST_TRANSLATE (
    Test_Name_Ru  varchar2(200),
    Test_Name_En  varchar2(200)
);

ALTER TABLE FACULTY
    ADD CONSTRAINT PK_FACULTY_LETTER PRIMARY KEY (FACULTY_LETTER);

ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT_ID PRIMARY KEY (STUDENT_ID);

ALTER TABLE TEST
    ADD CONSTRAINT PK_TEST_ID PRIMARY KEY (TEST_ID);

ALTER TABLE STUDENT_TEST
    ADD CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID);

ALTER TABLE STUDENT_TEST
    ADD CONSTRAINT FK_TEST_ID FOREIGN KEY (TEST_ID) REFERENCES TEST(TEST_ID);