-- 3.1.1

SELECT * FROM ALL_TABLES WHERE  rownum < 10
/

-- 3.1.2
SELECT * FROM SYSTEM_PRIVILEGE_MAP WHERE rownum < 10
/

-- 3.1.3
-- 3.2.1
CREATE TABLE MEMBERSHIP_TYPES (
    ID NUMBER NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    CONSTRAINT MEMBERSHIP_TYPES_PK PRIMARY KEY (ID)
)
/

CREATE TABLE MEMBERS
(
    ID NUMBER NOT NULL,
    DISCORD_ID NUMBER NOT NULL,
    NICKNAME VARCHAR(32) NOT NULL,
    MEMBERSHIP_DATE DATE NOT NULL,
    MEMBERSHIP_TYPE NUMBER NOT NULL,
    CONSTRAINT MEMBERS_PK PRIMARY KEY (ID),
    CONSTRAINT MEMBERS_FK FOREIGN KEY (MEMBERSHIP_TYPE) REFERENCES MEMBERSHIP_TYPES(ID)
)
/

SELECT * FROM ALL_TABLES WHERE  rownum < 10
/

SELECT * FROM USER_CONSTRAINTS

-- Именованное ограничение (исправил замечание)
ALTER TABLE EMP ADD CONSTRAINT SALARY_CONSTRAINT
CHECK (SAL BETWEEN 500 AND 5000)
/

INSERT INTO EMP(SAL) VALUES(5001)
/

ALTER TABLE EMP DROP CONSTRAINT SALARY_CONSTRAINT
/
-- Именованное ограничение

-- Неименованное ограничение (исправил замечание)
ALTER TABLE EMP ADD CHECK (SAL >= 500 AND SAL <= 5000)
/

INSERT INTO EMP(SAL) VALUES(5001)
/

SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'EMP' and SEARCH_CONDITION_VC = 'SAL >= 500 AND SAL <= 5000'
/

DECLARE
I NUMBER;
BEGIN
FOR I IN (
    SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'EMP' and SEARCH_CONDITION_VC = 'SAL >= 500 AND SAL <= 5000'
)
LOOP
EXECUTE IMMEDIATE('ALTER TABLE EMP DROP CONSTRAINT '|| I.CONSTRAINT_NAME);
END LOOP;
END;
/

SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'EMP' and SEARCH_CONDITION_VC = 'SAL >= 500 AND SAL <= 5000'
/
-- Неименованное ограничение

-- 3.3
CREATE INDEX I_DISCORD_ID ON MEMBERS(DISCORD_ID)
/

SELECT COUNT(*) from USER_INDEXES
/

CREATE TABLE DEPT_I (
    DEPTNO NUMBER(2,0) NOT NULL,
    DNAME VARCHAR (50),
    LOC VARCHAR(50),
    CONSTRAINT DEPT_I_PK PRIMARY KEY (DEPTNO)
)
ORGANIZATION INDEX
/

INSERT INTO DEPT_I
SELECT * FROM DEPT
/
