ALTER SESSION SET CURRENT_SCHEMA = STUDENT_DB;

UPDATE FACULTY
SET FACULTY_NAME_EN = (SELECT FACULTY_TRANSLATE.FACULTY_NAME_EN
            FROM FACULTY_TRANSLATE
            WHERE FACULTY_TRANSLATE.FACULTY_NAME_RU = FACULTY.FACULTY_NAME_RU);

UPDATE TEST
SET TEST_NAME_EN = (SELECT TEST_TRANSLATE.TEST_NAME_EN
            FROM TEST_TRANSLATE
            WHERE TEST_TRANSLATE.TEST_NAME_RU = TEST.TEST_NAME_RU);

-- DROP TABLE FACULTY_TRANSLATE;
-- DROP TABLE TEST_TRANSLATE;