CREATE TABLE TRIGGER_TABLE (ID NUMBER NOT NULL, MSG VARCHAR(64));
/

-- 5.1
CREATE SEQUENCE TRIGGER_SEQ MINVALUE 1 START WITH 50 INCREMENT BY 10 CACHE 20;
/

CREATE
OR REPLACE TRIGGER UPDATE_ID BEFORE INSERT ON TRIGGER_TABLE FOR EACH ROW
BEGIN
    SELECT TRIGGER_SEQ.NEXTVAL INTO :new.ID FROM DUAL;
END;
/

ALTER TRIGGER UPDATE_ID ENABLE;
/

INSERT INTO TRIGGER_TABLE(MSG) VALUES('ONE');
INSERT INTO TRIGGER_TABLE(MSG) VALUES('TWO');
INSERT INTO TRIGGER_TABLE(MSG) VALUES('THREE');
INSERT INTO TRIGGER_TABLE(MSG) VALUES('FOUR');
INSERT INTO TRIGGER_TABLE(MSG) VALUES('FIVE');
/

ALTER TRIGGER UPDATE_ID DISABLE;
/

SELECT * FROM TRIGGER_TABLE;
/

-- 5.2
CREATE
OR REPLACE TRIGGER UPDATE_ID_NOSEQ BEFORE INSERT ON TRIGGER_TABLE FOR EACH ROW
BEGIN
    SELECT COUNT(*) INTO :new.ID FROM TRIGGER_TABLE;
END;
/

ALTER TRIGGER UPDATE_ID_NOSEQ ENABLE;
/

INSERT INTO TRIGGER_TABLE(MSG) VALUES('ONE');
INSERT INTO TRIGGER_TABLE(MSG) VALUES('TWO');
INSERT INTO TRIGGER_TABLE(MSG) VALUES('THREE');
INSERT INTO TRIGGER_TABLE(MSG) VALUES('FOUR');
INSERT INTO TRIGGER_TABLE(MSG) VALUES('FIVE');
/

ALTER TRIGGER UPDATE_ID_NOSEQ DISABLE;
/

SELECT * FROM TRIGGER_TABLE;
/

-- 5.3
CREATE TABLE JOURNAL (OBJ_NAME VARCHAR(64) NOT NULL, EVENT VARCHAR(64) NOT NULL, EVENT_TIME DATE);
/

CREATE
OR REPLACE TRIGGER SCHEMA_LOGGER AFTER CREATE OR DROP OR ALTER ON SCHEMA
BEGIN
    INSERT INTO JOURNAL(OBJ_NAME, EVENT, EVENT_TIME) VALUES(ORA_DICT_OBJ_NAME, ORA_SYSEVENT, SYSDATE);
END;
/

ALTER TRIGGER SCHEMA_LOGGER ENABLE;

CREATE TABLE JOURNAL_TEST (OBJ_NAME VARCHAR(64) NOT NULL, EVENT VARCHAR(64) NOT NULL, EVENT_TIME DATE);
/

DROP TABLE JOURNAL_TEST;
/

SELECT * FROM JOURNAL;

-- 5.4
SELECT * FROM USER_TRIGGERS;
/